### ISSUE TITLE
`accelerationStructureCaptureReplayDescriptorDataSize` breaks the script

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/Vulkan-Profiles#484] opened 2023-08-21 20:59 UTC
Hi, the following Nvidia and AMD reports (both processed separately) break the Python script

[profiles.zip](https://github.com/LunarG/VulkanTools/files/12402451/profiles.zip)

Here's the backtrack
```
Traceback (most recent call last):
  File "gen_profiles_file.py", line 793, in <module>
    profile_merger.merge(jsons, profiles, profile_names, args.output_path, args.output_profile, args.profile_label, args.profile_desc, args.profile_api_version, profile_stage, profile_date, args.mode)
  File "gen_profiles_file.py", line 45, in merge
    merged['capabilities'] = self.merge_capabilities(jsons, profile_names, self.api_version)
  File "gen_profiles_file.py", line 132, in merge_capabilities
    self.add_members(merged_properties[property], capability['properties'][property], property)
  File "gen_profiles_file.py", line 408, in add_members
    xmlmember = self.registry.structs[property].members[member]
KeyError: 'accelerationStructureCaptureReplayDescriptorDataSize'
```

~~Should I be using a `vk.xml`  that is higher version than the reports?~~

The member is in the 1.3.250.1 SDK's provided vk.XML

**Comment by devshgraphicsprogramming** [comment] 2023-08-21 21:05
basically a 1.3.251 report breaks the python script, even if I use an up-to-date XML from Vulkan-Headers

**Comment by devshgraphicsprogramming** [comment] 2023-08-21 21:15
On an unsuccessful run it also prints:
```
member: accelerationStructureCaptureReplayDescriptorDataSize
member: accelerationStructureDescriptorSize
member: allowSamplerImageViewPostSubmitCreation
member: bufferCaptureReplayDescriptorDataSize
member: bufferlessPushDescriptors
member: combinedImageSamplerDescriptorSingleArray
member: combinedImageSamplerDescriptorSize
member: descriptorBufferAddressSpaceSize
member: descriptorBufferOffsetAlignment
member: imageCaptureReplayDescriptorDataSize
member: imageViewCaptureReplayDescriptorDataSize
member: inputAttachmentDescriptorSize
member: maxDescriptorBufferBindings
member: maxEmbeddedImmutableSamplerBindings
member: maxEmbeddedImmutableSamplers
member: maxResourceDescriptorBufferBindings
member: maxResourceDescriptorBufferRange
member: maxSamplerDescriptorBufferBindings
member: maxSamplerDescriptorBufferRange
member: resourceDescriptorBufferAddressSpaceSize
member: robustStorageBufferDescriptorSize
member: robustStorageTexelBufferDescriptorSize
member: robustUniformBufferDescriptorSize
member: robustUniformTexelBufferDescriptorSize
member: sampledImageDescriptorSize
member: samplerCaptureReplayDescriptorDataSize
member: samplerDescriptorBufferAddressSpaceSize
member: samplerDescriptorSize
member: storageBufferDescriptorSize
member: storageImageDescriptorSize
member: storageTexelBufferDescriptorSize
member: uniformBufferDescriptorSize
member: uniformTexelBufferDescriptorSize
```
before crashing.

So I think we hit this code:
```py
        # First, remove all noauto member, they can't be merged
        if property != None:
            for member in list(merged):
                if (member not in self.registry.structs[property].members):
                    print('member: ' + member)
                    continue

                xmlmember = self.registry.structs[property].members[member]
                if xmlmember.limittype == 'noauto':
                    del merged[member]
                #elif 'mul'  in xmlmember.limittype and xmlmember.type == 'float':
                #    del merged[member]
                ```

**Comment by devshgraphicsprogramming** [comment] 2023-08-21 21:20
hmm looks like @SaschaWillems 's caps-viewer produces incorrect JSONS
```json

                "VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT": {
                    "accelerationStructureCaptureReplayDescriptorDataSize": "4",
                    "accelerationStructureDescriptorSize": "16",
                    "allowSamplerImageViewPostSubmitCreation": "true",
                    "bufferCaptureReplayDescriptorDataSize": "4",
                    "bufferlessPushDescriptors": "true",
                    "combinedImageSamplerDescriptorSingleArray": "true",
                    "combinedImageSamplerDescriptorSize": "48",
                    "descriptorBufferAddressSpaceSize": "4294967295",
                    "descriptorBufferOffsetAlignment": "16",
                    "imageCaptureReplayDescriptorDataSize": "4",
                    "imageViewCaptureReplayDescriptorDataSize": "4",
                    "inputAttachmentDescriptorSize": "32",
                    "maxDescriptorBufferBindings": "32",
                    "maxEmbeddedImmutableSamplerBindings": "32",
                    "maxEmbeddedImmutableSamplers": "4294967295",
                    "maxResourceDescriptorBufferBindings": "32",
                    "maxResourceDescriptorBufferRange": "4294967295",
                    "maxSamplerDescriptorBufferBindings": "32",
                    "maxSamplerDescriptorBufferRange": "4294967295",
                    "resourceDescriptorBufferAddressSpaceSize": "4294967295",
                    "robustStorageBufferDescriptorSize": "16",
                    "robustStorageTexelBufferDescriptorSize": "16",
                    "robustUniformBufferDescriptorSize": "16",
                    "robustUniformTexelBufferDescriptorSize": "16",
                    "sampledImageDescriptorSize": "32",
                    "samplerCaptureReplayDescriptorDataSize": "4",
                    "samplerDescriptorBufferAddressSpaceSize": "4294967295",
                    "samplerDescriptorSize": "16",
                    "storageBufferDescriptorSize": "16",
                    "storageImageDescriptorSize": "32",
                    "storageTexelBufferDescriptorSize": "16",
                    "uniformBufferDescriptorSize": "16",
                    "uniformTexelBufferDescriptorSize": "16"
                },
```

**Comment by SaschaWillems** [comment] 2023-08-22 15:25
The caps-viewer **does not generate any profile JSONs** at all. Do you mean the profile jsons downloaded from the database?

**Comment by devshgraphicsprogramming** [comment] 2023-08-23 06:36
> The caps-viewer **does not generate any profile JSONs** at all. Do you mean the profile jsons downloaded from the database?

Yes, pretty much any profile JSON downloaded for any AMD or Nvidia device with the API version > 1.3.250 has this bug.

**Comment by ziga-lunarg** [comment] 2023-10-23 17:14
@devshgraphicsprogramming Did the fix from @SaschaWillems on his side fix this issue? 

The profiles you posted in the original message are not valid, I'm seeing the following error running it against the latest schema: 

```
Error #1
         context: <root>[capabilities][device][properties][VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT]
         desc:    Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: 'accelerationStructureCaptureReplayDescriptorDataSize'.
```

**Comment by devshgraphicsprogramming** [comment] 2023-11-02 08:17
> @devshgraphicsprogramming Did the fix from @SaschaWillems on his side fix this issue?
> 
> The profiles you posted in the original message are not valid, I'm seeing the following error running it against the latest schema:
> 
> ```
> Error #1
>          context: <root>[capabilities][device][properties][VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT]
>          desc:    Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: 'accelerationStructureCaptureReplayDescriptorDataSize'.
> ```

haven't came back to the topic since August, I guess grab any >=1.3.251 report from gpuinfo and see.

**Comment by christophe-lunarg** [comment] 2023-11-15 12:49
I can confirm the issue is fixed in current GPUinfo.org.

Tehre is another issue however with `VkPhysicalDeviceHostImageCopyPropertiesEXT` that we are not supporting because the design of this extension is messed up so we black listed it.

**Closed by christophe-lunarg** 2023-11-15 12:49 UTC
