### ISSUE TITLE
Differences in profile support with newer profiles library version

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#607] opened 2024-02-07 17:36 UTC
After updating the profiles library in my Vulkan Hardware Capability Viewer (using the roadmap 2024 tag), I noticed that some LunarG profiles that were marked as supported by an older version of the library are now now longer supported on my setup. Here is the same version of my app running simultaneously, one with an older profile library and one with the recent version:

![image](https://github.com/KhronosGroup/Vulkan-Profiles/assets/10283127/11ed6b68-8c99-4091-bd50-106290aa16ec)

You can see that e.g. `VP_LUNARG_desktop_baseline_2022/23` are no longer reported as supported, even though their (spec) version is still the same. Is that correct?

**Comment by christophe-lunarg** [comment] 2024-02-07 18:32
Hi Sascha,

This is very weird, can you share a profile JSON file for your device? :D
But something is deeply weird. The LUNARG_minimum_requirements* are just the minimum requirements of Vulkan 1.*.

Thanks!

**Comment by SaschaWillems** [comment] 2024-02-07 18:41
Sure, here you go: 
[VP_VULKANINFO_NVIDIA_GeForce_RTX_4070_538_31_0_0.json](https://github.com/KhronosGroup/Vulkan-Profiles/files/14200194/VP_VULKANINFO_NVIDIA_GeForce_RTX_4070_538_31_0_0.json)

Created with vulkaninfoSDK from SDK 1.3.275

**Comment by SaschaWillems** [comment] 2024-02-13 19:54
I tried to debug this, but it's pretty hard (for me) to debug the generated code of the library. This is as far as I got:

![image](https://github.com/KhronosGroup/Vulkan-Profiles/assets/10283127/936f20cc-5d71-4e61-9a34-789b80b9ac70)

I can only guess that one of those features isn't supported by the GPU. But that would mean that newer versions of the library have additional checks for already existing profiles without e.g. increasing their version.

**Comment by christophe-lunarg** [comment] 2024-02-14 19:39
Something is clearly wrong, I manage to reproduce the bug, I'll let you know, I will hopefully have a fix tomorrow!

**Comment by christophe-lunarg** [comment] 2024-02-15 19:23
@SaschaWillems, this is fixed by https://github.com/KhronosGroup/Vulkan-Profiles/pull/614. The issue is relative to properties that have a feature dependence and change values based on the feature support or not. Annoying. There were also issue in the definision that I resolved. I am not totally convinved by the fix but I'll need vk.xml adding such dependences to be satisfied and that's a stretch goal!

**Comment by SaschaWillems** [comment] 2024-02-15 21:12
I'm not sure. This is for my RTX 4070 with the latest Vulkan developer driver:

![image](https://github.com/KhronosGroup/Vulkan-Profiles/assets/10283127/190706a7-3d86-43fe-aa2a-7450d6034f62)

I would expect it to support the desktop baseline profiles.

**Comment by SaschaWillems** [comment] 2024-02-20 20:33
Looks better now. But I'm not 100% sure yet. It still reports "VP_LUNARG_desktop_baseline_2024" as unsupported. So I checked my device (RTX 4070, latest Vulkan Developer driver) with the requirements from https://vulkan.lunarg.com/doc/sdk/1.3.275.0/windows/profiles_definitions.html and could not find why that profile is still reported as unsupported. Is there a way for you to check what's lacking or if it's reported wrong?

**Comment by christophe-lunarg** [comment] 2024-02-20 20:38
> Looks better now. But I'm not 100% sure yet. It still reports "VP_LUNARG_desktop_baseline_2024" as unsupported. So I checked my device (RTX 4070, latest Vulkan Developer driver) with the requirements from https://vulkan.lunarg.com/doc/sdk/1.3.275.0/windows/profiles_definitions.html and could not find why that profile is still reported as unsupported. Is there a way for you to check what's lacking or if it's reported wrong?

I'll installed the developer drivers tomorrow. The profile is supported on my 3080 so it should work but I'll see.

**Comment by christophe-lunarg** [comment] 2024-02-22 14:08
I installed the new NVIDIA developer driver and I am getting this message when using the debug version of the API library:
Unsupported properties condition: VkPhysicalDeviceSubgroupSizeControlPropertiesEXT::maxComputeWorkgroupSubgroups >= 56
E:\Github\khronos\Vulkan-Profiles-Dev\library\test\test_api_create_device.cpp(120): error: Value of: supported == 1U
  Actual: false
Expected: true

I uploaded my system report here: 
https://vulkan.gpuinfo.org/displayreport.php?id=28381

And we can see that the driver now reports:
<html>
<body>

VK_EXT_subgroup_size_control
--
maxComputeWorkgroupSubgroups | 32
maxSubgroupSize | 32
minSubgroupSize | 32
requiredSubgroupSizeStages | 16383


</body>
</html>

Which is a changed compared with older drivers version (here with Vulkan API 271):
https://vulkan.gpuinfo.org/displayreport.php?id=27779#properties_extensions

Maybe that's a drivers bug... But the Vulkan API library is working fine. 
If it's not a bug but a fix then probably the definision of the Desktop Baseline 2024 profile will need to change.

Thanks!

**Closed by christophe-lunarg** 2024-02-22 14:08 UTC
Labels: bug, OS - Platform Independent, P0 - Must Fix

**Comment by christophe-lunarg** [comment] 2024-02-26 16:32
@SaschaWillems : Following the discussion with Piers, I am updaing the desktop baseline 2024 profile to reflect on the driver fix.

This is done with https://github.com/KhronosGroup/Vulkan-Profiles/pull/628

Thanks!

**Comment by SaschaWillems** [comment] 2024-03-03 10:42
With the latest Vulkan Developer driver I still get the desktop_baseline_2024 reported as unsupported on an RTX 4070 and Windows 11. Is that correct?

**Comment by christophe-lunarg** [comment] 2024-03-05 11:45
Hi Sascha,

I just installed the latest NVIDIA developer drivers (for Vulkan API 1.3.278) and I couldn't reproduce the issue on `main` branch on a RTX 3080 ti.

Attached the debug and release build of the library.
