### ISSUE TITLE
Incorrect lineWidthGranularity check in profile library (2022 roadmap)

### ISSUE THREAD

**Issue by jantho-arm** [KhronosGroup/Vulkan-Profiles#321] opened 2022-11-08 19:09 UTC
For the 2022 roadmap, the profiles library has the following checks for `lineWidthGranularity`:

```
  ret = ret && (s->properties.limits.lineWidthGranularity <= 0.5);
  ret = ret && (isMultiple(0.5, s->properties.limits.lineWidthGranularity));
```

The second check fails if `lineWidthGranularity` is 0, which should be allowed by the profile if the `wideLines` feature is not supported (only the _supported_ limit was lowered from 1.0 to 0.5, the _unsupported_ limit is still 0.0).

Further, it doesn't really make sense to check that the `lineWidthGranularity` is a multiple of anything, since as far as I can tell that is not required by the Vulkan specification. Perhaps instead it should be checking that the `lineWidthRange` is a multiple of the `lineWidthGranularity` (but only if `wideLines` is supported)?

**Comment by janharaldfredriksen-arm** [comment] 2022-11-14 10:20
@christophe-lunarg - thoughts?

**Comment by christophe-lunarg** [comment] 2022-11-16 11:52
Hi,

I think you are absolutely right, 
```
  ret = ret && (isMultiple(0.5, s->properties.limits.lineWidthGranularity));
```
doesn't make any sense in this context and I'll fix it. It's actually only potentially useful for the Profiles layer because we override  the driver value but we must override it with a relevant value.

Thanks for reporting, that will be fixed for next SDK most likely today!

**Comment by christophe-lunarg** [comment] 2022-11-16 13:55
Still investigating...

**Comment by christophe-lunarg** [comment] 2022-11-16 15:12
@jantho-arm, @janharaldfredriksen-arm I think the issue is actually not with the library but the limittype for `pointSizeGranularity` and `lineWidthGranularity` in vk.xml that is specified incorrectly to `min,mul` but I think it should be just `min`.

**Comment by janharaldfredriksen-arm** [comment] 2022-11-16 15:32
I think there's two issues here.

1) The (min,mul) limittype seems odd.  The spec describes the lineWidthGranularity as having a "max, fixed point increment" type. It's not very clear, but my understanding was that the intent here is that the supported _line widths_ are a multiple of lineWidthGranularity. E.g with the 2022 roadmap limit, the supported line widths are at least 0.5, 1.0, 1.5, etc.
It makes sense to treat this as a spec issue.

2) The wideLines feature itself isn't required in the 2022 roadmap.
I think conceptually, the lineWidthGranularity granularity checks need to be conditional on this, i.e., in pseudo code:

```
if (wideLines)
{
  ret = ret && (s->properties.limits.lineWidthGranularity <= 0.5);
  ret = ret && (isMultiple(0.5, s->properties.limits.lineWidthGranularity));
}
```

**Comment by christophe-lunarg** [comment] 2022-11-16 16:24
Erm, then this conditional is pretty tricky... it's pretty must that there are two Roadmap 2022 profiles instead of one...

I am trying to figure out how this could be expressed but I am having a hard time...

**Comment by janharaldfredriksen-arm** [comment] 2022-12-14 16:20
Does this become easier to express with the changes in 1.3.236 spec update, or would we expect this to 'just work' with an SDK matching that version?

**Comment by christophe-lunarg** [comment] 2023-01-06 16:06
With the spec changes, it will just work. It would be nice to check if a profile is supported including the optionals features but this is a future improvement.

I am considering this issue resolved but if you have more comments feel with to share or even reopen the issue if you think I am wrong.

Thanks for testing and reporting this!

**Closed by christophe-lunarg** 2023-01-06 16:06 UTC
Labels: bug, OS - Platform Independent, P0 - Must Fix
